spring:
  data:
    mongodb:
      username: jiacheng
      password: Igf8%*fg6$%gftdf
      database: TweetScraper
      port: 27017
      host: 119.45.163.114

runtime: java
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored